# Generated by Django 5.0.6 on 2024-07-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mytiktok", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
